@startuml
participant IDB as "IndexDB"
participant STR as "Local Storage"
participant FE as "Module FE"
participant REST as "REST"
participant BE as "Module BE"
participant FS as "Firestore"
participant FB as "Firebase"

== Upsert in BE ==
FE -> BE: perform a change
BE -> FS: make a change in DB
BE -> FB: set **lastUpdatedBE**

== Check if Sync Needed ==
FB -> FE: update on last update change
FE -> FE: Check Delta sync timestamp
FE -> FE: if (**lastUpdatedBE** > **lastUpdatedFE** ) trigger sync

== Sync ==
FE <-> STR: get **lastUpdatedFE**
FE -> BE: get all new data\nafter **lastUpdatedFE**
BE <-> FS: Fetch all new data
BE -> FE: return new Data
FE -> IDB: upsert new data + delete deleted documents
FE -> STR: set **lastUpdatedFE**


@enduml