import {TestSuite} from '../../main/testing/types';
import {debounce, timeout} from '../../main';
import {runSingleTestCase} from '../../main/testing/consts';

export type Input = {
	timer?: number;
	repeats: number;
};

export type Result = { value: number };
export type TestSuite_Debounce = TestSuite<Input, Result>;
export type TestCase_Debounce = TestSuite_Debounce['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	let counter = 0;
	const fn = debounce(() => counter++, input.timer);
	for (let i = 0; i < input.repeats; i++) {
		fn();
		await timeout(200);
	}
	await timeout(2000);
	return {value: counter};
};

const runTestCase = (testCase: TestCase_Debounce) => {
	return () => runSingleTestCase(test, testCase);
};

describe('debounce', () => {
	it('Debounce with custom timer runs 2 times', runTestCase({
		input: {timer: 1000, repeats: 5},
		result: {value: 2}
	}));

	it('Debounce with default timer runs 2 times', runTestCase({
		input: {repeats: 5},
		result: {value: 2}
	}));

	// Generated by ChatGPT - 2025-05-26T00:15
	it('GPT - Debounce fires once with a single call', runTestCase({
		input: {repeats: 1},
		result: {value: 1}
	}));
});
