import {filterFalsy, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
};

export type Result = any[];
export type TestSuite_filterFalsy = TestSuite<Input, Result>;
export type TestCase_filterFalsy = TestSuite_filterFalsy['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return filterFalsy(input.array);
};

const runTestCase = (testCase: TestCase_filterFalsy) => {
	return () => runSingleTestCase(test, testCase);
};

describe('filterFalsy', () => {
	it('Removes 0 and null from numeric array', runTestCase({
		input: {array: [1, 2, 3, 0, null]},
		result: [1, 2, 3]
	}));

	it('Removes empty string and undefined', runTestCase({
		input: {array: [1, 2, 3, '', undefined]},
		result: [1, 2, 3]
	}));

	it('Keeps objects, removes empty string and undefined', runTestCase({
		input: {array: [1, 2, 3, '', undefined, {}]},
		result: [1, 2, 3, {}]
	}));

	it('Removes false along with other falsy values', runTestCase({
		input: {array: [1, 2, 3, '', undefined, {}, false]},
		result: [1, 2, 3, {}]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Removes NaN and false from mixed types', runTestCase({
		input: {array: [0, 1, NaN, 2, false, 3]},
		result: [1, 2, 3]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Keeps empty arrays and objects', runTestCase({
		input: {array: [[], {}, '', undefined, null]},
		result: [[], {}]
	}));
});
