// file: ./tests/filter/filterAsync.test.ts

import {filterAsync, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
	filter: (item: T) => Promise<boolean>;
};

export type Result = any[];
export type TestSuite_filterAsync = TestSuite<Input, Result>;
export type TestCase_filterAsync = TestSuite_filterAsync['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return filterAsync(input.array, input.filter);
};

const runTestCase = (testCase: TestCase_filterAsync) => {
	return () => runSingleTestCase(test, testCase);
};

describe('filterAsync', () => {
	it('Filters even numbers from a numeric array', runTestCase({
		input: {
			array: [1, 2, 3, 4, 5, 6, 7],
			filter: async (n: number) => n % 2 === 0
		},
		result: [2, 4, 6]
	}));

	it('Filters out string values', runTestCase({
		input: {
			array: ['1', '{}', 3, 4, 5, 6, 7],
			filter: async (n: any) => typeof n !== 'string'
		},
		result: [3, 4, 5, 6, 7]
	}));

	it('Filters objects only', runTestCase({
		input: {
			array: [1, 2, {}, {a: 5}, {b: 5}],
			filter: async (n: any) => typeof n === 'object'
		},
		result: [{}, {a: 5}, {b: 5}]
	}));

	it('Filters primitives only', runTestCase({
		input: {
			array: ['one', {a: 3}, 5, {}],
			filter: async (item: any) => typeof item !== 'object'
		},
		result: ['one', 5]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Filters out falsy values', runTestCase({
		input: {
			array: [0, null, undefined, '', false, 'valid', 123],
			filter: async (item: any) => Boolean(item)
		},
		result: ['valid', 123]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Filters values after async delay greater than 3', runTestCase({
		input: {
			array: [1, 2, 3, 4, 5],
			filter: async (n: number) => {
				await new Promise(r => setTimeout(r, 10));
				return n > 3;
			}
		},
		result: [4, 5]
	}));
});
