import {filterInstances} from '../../_main.js';
import {runSingleTestCase, TestModel} from '@nu-art/testalot';

export type Input<T = any> = {
	array: T[];
};

export type Result = any[];
export type TestCase_filterInstances = TestModel<Input, Result>;

const test = async (input: Input): Promise<Result> => {
	return filterInstances(input.array);
};

const runTestCase = (testCase: TestCase_filterInstances) => {
	return () => runSingleTestCase(test, testCase);
};

describe('filterInstances', () => {
	it('Keeps non-null values including 0', runTestCase({
		input: {array: [1, 2, 3, 0, null]},
		result: [1, 2, 3, 0]
	}));

	it('Keeps numbers and empty string, filters out undefined', runTestCase({
		input: {array: [1, 2, 3, '', undefined]},
		result: [1, 2, 3, '']
	}));

	it('Keeps objects and empty string, filters undefined', runTestCase({
		input: {array: [1, 2, 3, '', undefined, {}]},
		result: [1, 2, 3, '', {}]
	}));

	it('Keeps all defined values including false and empty string', runTestCase({
		input: {array: [1, 2, 3, '', undefined, {}, false]},
		result: [1, 2, 3, '', {}, false]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Filters out only undefined and null, keeps falsy values', runTestCase({
		input: {array: [null, undefined, '', 0, false, NaN]},
		result: ['', 0, false, NaN]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Keeps custom class instances', () => {
		const fooClass = class Foo {
		};
		const fooClassInstance = new fooClass();
		runTestCase({
			input: {
				array: [
					fooClass,
					fooClassInstance,
					undefined,
					null
				]
			},
			result: [
				fooClass,
				fooClassInstance
			]
		});
	});

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Keeps arrays and plain objects, filters nulls', () => {
		const emptyArray: [] = [];
		const emptyObj = {};
		const arrayOf1 = [1];
		const objectOfX1 = {x: 1};
		runTestCase({
			input: {array: [emptyArray, emptyObj, null, arrayOf1, objectOfX1]},
			result: [emptyArray, emptyObj, arrayOf1, objectOfX1]
		});
	});
});
