import {filterInstances, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
};

export type Result = any[];
export type TestSuite_filterInstances = TestSuite<Input, Result>;
export type TestCase_filterInstances = TestSuite_filterInstances['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return filterInstances(input.array);
};

const runTestCase = (testCase: TestCase_filterInstances) => {
	return () => runSingleTestCase(test, testCase);
};

describe('filterInstances', () => {
	it('Keeps non-null values including 0', runTestCase({
		input: {array: [1, 2, 3, 0, null]},
		result: [1, 2, 3, 0]
	}));

	it('Keeps numbers and empty string, filters out undefined', runTestCase({
		input: {array: [1, 2, 3, '', undefined]},
		result: [1, 2, 3, '']
	}));

	it('Keeps objects and empty string, filters undefined', runTestCase({
		input: {array: [1, 2, 3, '', undefined, {}]},
		result: [1, 2, 3, '', {}]
	}));

	it('Keeps all defined values including false and empty string', runTestCase({
		input: {array: [1, 2, 3, '', undefined, {}, false]},
		result: [1, 2, 3, '', {}, false]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Filters out only undefined and null, keeps falsy values', runTestCase({
		input: {array: [null, undefined, '', 0, false, NaN]},
		result: ['', 0, false, NaN]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Keeps custom class instances', runTestCase({
		input: {
			array: [
				class Foo {}, new (class Foo {})(),
				undefined, null
			]
		},
		result: [class Foo {}, new (class Foo {})()]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Keeps arrays and plain objects, filters nulls', runTestCase({
		input: {array: [[], {}, null, [1], {x: 1}]},
		result: [[], {}, [1], {x: 1}]
	}));
});
