import {findDuplicates, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array1: T[];
	array2: T[];
};

export type Result = any[];
export type TestSuite_findDuplicates = TestSuite<Input, Result>;
export type TestCase_findDuplicates = TestSuite_findDuplicates['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return findDuplicates(input.array1, input.array2);
};

const runTestCase = (testCase: TestCase_findDuplicates) => {
	return () => runSingleTestCase(test, testCase);
};

const emptyObj = {};

describe('findDuplicates', () => {
	it('Finds shared numeric elements in order', runTestCase({
		input: {array1: [1, 2, 3], array2: [1, 2, 3, 4]},
		result: [1, 2, 3]
	}));

	it('Finds shared object reference between arrays', runTestCase({
		input: {array1: [emptyObj], array2: [emptyObj]},
		result: [emptyObj]
	}));

	it('Finds all items in reversed arrays', runTestCase({
		input: {array1: [1, 2, 3, 4, 5], array2: [5, 4, 3, 2, 1]},
		result: [1, 2, 3, 4, 5]
	}));

	it('Includes repeated matches if repeated in first array', runTestCase({
		input: {array1: [1, 2, 3, 4, 5, 1], array2: [5, 1]},
		result: [1, 5, 1]
	}));

	it('Matches duplicates respecting quantity in array1', runTestCase({
		input: {array1: [5, 1, 5], array2: [5, 1, 1, 1, 1]},
		result: [5, 1, 5]
	}));

	it('No common elements between arrays', runTestCase({
		input: {array1: [1, 'a'], array2: [2, 3, 'b']},
		result: []
	}));

	it('All elements in array1 are the same and found in array2 once', runTestCase({
		input: {array1: [1, 1, 1, 1, 1, 1, 1, 1, 1], array2: [1]},
		result: [1, 1, 1, 1, 1, 1, 1, 1, 1]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Finds duplicates among mixed types (string and number)', runTestCase({
		input: {array1: ['5', 5, '10'], array2: [5, '5']},
		result: ['5', 5]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Handles empty array1 gracefully', runTestCase({
		input: {array1: [], array2: [1, 2, 3]},
		result: []
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Handles both arrays empty', runTestCase({
		input: {array1: [], array2: []},
		result: []
	}));
});
