import {flatArray, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
	result: T[];
};

export type Result = any[];
export type TestSuite_flatArray = TestSuite<Input, Result>;
export type TestCase_flatArray = TestSuite_flatArray['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return flatArray(input.array, input.result);
};

const runTestCase = (testCase: TestCase_flatArray) => {
	return () => runSingleTestCase(test, testCase);
};

describe('flatArray', () => {
	it('Flattens two arrays of numbers into a single array', runTestCase({
		input: {
			array: [[1, 2, 3], [5, 6, 7]],
			result: []
		},
		result: [1, 2, 3, 5, 6, 7]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Flattens arrays of strings', runTestCase({
		input: {
			array: [['a', 'b'], ['c', 'd']],
			result: []
		},
		result: ['a', 'b', 'c', 'd']
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Flattens with existing result array provided', runTestCase({
		input: {
			array: [[4, 5], [6]],
			result: [1, 2, 3]
		},
		result: [1, 2, 3, 4, 5, 6]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Handles empty input array', runTestCase({
		input: {
			array: [],
			result: []
		},
		result: []
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Handles nested empty arrays', runTestCase({
		input: {
			array: [[], [], []],
			result: []
		},
		result: []
	}));
});
