import {groupArrayBy, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
	mapper: (item: T) => any;
};

export type Result = any[];
export type TestSuite_groupArrayBy = TestSuite<Input, Result>;
export type TestCase_groupArrayBy = TestSuite_groupArrayBy['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return groupArrayBy(input.array, input.mapper);
};

const runTestCase = (testCase: TestCase_groupArrayBy) => {
	return () => runSingleTestCase(test, testCase);
};

describe('groupArrayBy', () => {
	it('Groups people by numeric age key', runTestCase({
		input: {
			array: [
				{age: 0, gender: 'male'},
				{age: 0, gender: 'female'},
				{age: 1, gender: 'male'}
			],
			mapper: item => item.age
		},
		result: [
			{key: '0', values: [{age: 0, gender: 'male'}, {age: 0, gender: 'female'}]},
			{key: '1', values: [{age: 1, gender: 'male'}]}
		]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Groups words by first letter', runTestCase({
		input: {
			array: ['apple', 'apricot', 'banana', 'blueberry'],
			mapper: word => word[0]
		},
		result: [
			{key: 'a', values: ['apple', 'apricot']},
			{key: 'b', values: ['banana', 'blueberry']}
		]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Groups by boolean condition (even/odd)', runTestCase({
		input: {
			array: [1, 2, 3, 4, 5, 6],
			mapper: n => n % 2 === 0
		},
		result: [
			{key: 'false', values: [1, 3, 5]},
			{key: 'true', values: [2, 4, 6]}
		]
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Handles empty input array', runTestCase({
		input: {
			array: [],
			mapper: () => 'any'
		},
		result: []
	}));

	// Generated by ChatGPT - 2025-05-25T23:00
	it('GPT - Groups by constant key (all in one group)', runTestCase({
		input: {
			array: ['a', 'b', 'c'],
			mapper: () => 'all'
		},
		result: [
			{key: 'all', values: ['a', 'b', 'c']}
		]
	}));
});
