import {removeFromArray, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
	item: (item: T) => boolean;
};

export type Result = any[];
export type TestSuite_removeFromArray = TestSuite<Input, Result>;
export type TestCase_removeFromArray = TestSuite_removeFromArray['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return removeFromArray(input.array, input.item);
};

const runTestCase = (testCase: TestCase_removeFromArray) => {
	return () => runSingleTestCase(test, testCase);
};

describe('removeFromArray', () => {
	it('Removes even number (2) from array', runTestCase({
		input: {
			array: [1, 2, 3],
			item: item => item % 2 === 0
		},
		result: [1, 3]
	}));

	it('Removes last odd number from array of mostly evens', runTestCase({
		input: {
			array: [4, 8, 10, 9],
			item: item => item % 2 === 1
		},
		result: [4, 8, 10]
	}));

	it('Removes object matching JSON of {a: 3}', runTestCase({
		input: {
			array: [{a: 1}, {a: 2}, {a: 3}],
			item: item => JSON.stringify(item) === JSON.stringify({a: 3})
		},
		result: [{a: 1}, {a: 2}]
	}));

	it('Removes specific string value "three"', runTestCase({
		input: {
			array: ['one', 'two', 'three'],
			item: item => item === 'three'
		},
		result: ['one', 'two']
	}));

	it('Does not remove non-matching object by different property order', runTestCase({
		input: {
			array: [{a: 1}, {a: 2}, {b: 5, a: 3}],
			item: item => JSON.stringify(item) === JSON.stringify({a: 3, b: 5})
		},
		result: [{a: 1}, {a: 2}, {b: 5, a: 3}]
	}));

	// Generated by ChatGPT - 2025-05-25T23:20
	it('GPT - Removes all strings of length 3', runTestCase({
		input: {
			array: ['cat', 'dog', 'tree', 'fish'],
			item: item => typeof item === 'string' && item.length === 3
		},
		result: ['tree', 'fish']
	}));

	// Generated by ChatGPT - 2025-05-25T23:20
	it('GPT - Removes NaN values', runTestCase({
		input: {
			array: [1, NaN, 2, NaN, 3],
			item: item => Number.isNaN(item)
		},
		result: [1, 2, 3]
	}));

	// Generated by ChatGPT - 2025-05-25T23:20
	it('GPT - Handles empty array gracefully', runTestCase({
		input: {
			array: [],
			item: () => true
		},
		result: []
	}));
});
