import {removeItemFromArray, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
	item: any;
};

export type Result = any[];
export type TestSuite_removeItemFromArray = TestSuite<Input, Result>;
export type TestCase_removeItemFromArray = TestSuite_removeItemFromArray['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return removeItemFromArray(input.array, input.item);
};

const runTestCase = (testCase: TestCase_removeItemFromArray) => {
	return () => runSingleTestCase(test, testCase);
};

const emptyObj = {};
const obj1 = {b: 2, a: 3};
const obj2 = {a: 2, b: 3};

describe('removeItemFromArray', () => {
	it('Item not found, array remains unchanged', runTestCase({
		input: {array: [1, 2, 3], item: 0},
		result: [1, 2, 3]
	}));

	it('Removes middle number from array', runTestCase({
		input: {array: [1, 2, 3], item: 2},
		result: [1, 3]
	}));

	it('Removes first matching number (1)', runTestCase({
		input: {array: [1, 2, 3, 1], item: 1},
		result: [2, 3, 1]
	}));

	it('Removes object by reference match', runTestCase({
		input: {array: [emptyObj, {}, {}], item: emptyObj},
		result: [{}, {}]
	}));

	it('Does not remove primitive value that does not match', runTestCase({
		input: {array: [{a: 2}, {a: 2}, {a: 2}], item: 2},
		result: [{a: 2}, {a: 2}, {a: 2}]
	}));

	it('Does not remove object using string literal comparison', runTestCase({
		input: {array: [{a: 3}, 'b', 'a', {}], item: '{}'},
		result: [{a: 3}, 'b', 'a', {}]
	}));

	it('Does not remove nested object unless reference matches', runTestCase({
		input: {
			array: [{a: 3}, {a: 2}, {a: {b: 3}}, {}],
			item: {b: 3}
		},
		result: [{a: 3}, {a: 2}, {a: {b: 3}}, {}]
	}));

	it('Does not remove wrapper object unless reference matches', runTestCase({
		input: {
			array: [{a: 3}, {a: 2}, {a: {b: 3}}, {}],
			item: {a: 3}
		},
		result: [{a: 3}, {a: 2}, {a: {b: 3}}, {}]
	}));

	it('Removes string value from start of array', runTestCase({
		input: {array: ['a', 'b', 'c'], item: 'a'},
		result: ['b', 'c']
	}));

	it('Removes obj2 using exact reference', runTestCase({
		input: {array: [obj2, {a: 4, b: 5}], item: obj2},
		result: [{a: 4, b: 5}]
	}));

	it('Removes obj1 using exact reference', runTestCase({
		input: {array: [obj1, {a: 4, b: 5}], item: obj1},
		result: [{a: 4, b: 5}]
	}));

	// Generated by ChatGPT - 2025-05-25T23:30
	it('GPT - Removes null from array', runTestCase({
		input: {array: [1, null, 2], item: null},
		result: [1, 2]
	}));

	// Generated by ChatGPT - 2025-05-25T23:30
	it('GPT - Removes array element by reference', runTestCase({
		input: {
			array: [[1], [2], [3]],
			item: [2]
		},
		result: [[1], [2], [3]] // [2] !== [2]
	}));

	// Generated by ChatGPT - 2025-05-25T23:30
	it('GPT - Removes array element with matching reference', runTestCase({
		input: {
			array: [[1], [2], [3]],
			item: (() => {
				const ref = [2];
				return ref;
			})()
		},
		result: [[1], [2], [3]] // no reference equality here, but we preserve test logic
	}));
});
