import {removeFromArrayByIndex, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
	index: number;
};

export type Result = any[];
export type TestSuite_removeFromArrayByIndex = TestSuite<Input, Result>;
export type TestCase_removeFromArrayByIndex = TestSuite_removeFromArrayByIndex['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return removeFromArrayByIndex(input.array, input.index);
};

const runTestCase = (testCase: TestCase_removeFromArrayByIndex) => {
	return () => runSingleTestCase(test, testCase);
};

describe('removeFromArrayByIndex', () => {
	it('Removes first item (index 0)', runTestCase({
		input: {array: [0, 1, 2, 3], index: 0},
		result: [1, 2, 3]
	}));

	it('Removes only item from single-element array', runTestCase({
		input: {array: [0], index: 0},
		result: []
	}));

	it('Index out of bounds (1) on single-element array does nothing', runTestCase({
		input: {array: [0], index: 1},
		result: [0]
	}));

	it('Removes middle item (index 1)', runTestCase({
		input: {array: [1, 2, 3], index: 1},
		result: [1, 3]
	}));

	it('No-op on empty array', runTestCase({
		input: {array: [], index: 1},
		result: []
	}));

	it('Negative index is ignored', runTestCase({
		input: {array: [1, 2, 3], index: -21},
		result: [1, 2, 3]
	}));

	it('Removes object at index 2 from array of objects', runTestCase({
		input: {array: [{}, {}, {}, {}], index: 2},
		result: [{}, {}, {}]
	}));

	// Generated by ChatGPT - 2025-05-25T23:25
	it('GPT - Removes last item from long array', runTestCase({
		input: {
			array: Array.from({length: 10}, (_, i) => i),
			index: 9
		},
		result: [0, 1, 2, 3, 4, 5, 6, 7, 8]
	}));

	// Generated by ChatGPT - 2025-05-25T23:25
	it('GPT - Index exceeds array length', runTestCase({
		input: {
			array: [1, 2],
			index: 5
		},
		result: [1, 2]
	}));
});
