import {sortArray, runSingleTestCase, TestSuite} from '../../_main';

export type Input<T = any> = {
	array: T[];
	map: (item: T) => any;
	invert?: boolean;
};

export type Result = any[];
export type TestSuite_sortArray = TestSuite<Input, Result>;
export type TestCase_sortArray = TestSuite_sortArray['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return sortArray(input.array, input.map, input.invert);
};

const runTestCase = (testCase: TestCase_sortArray) => {
	return () => runSingleTestCase(test, testCase);
};

describe('sortArray', () => {
	it('Sorts objects by numeric shoeSize ascending', runTestCase({
		input: {
			array: [
				{name: 'Alon', shoeSize: 47.5},
				{name: 'Itay', shoeSize: 50},
				{name: 'Adam', shoeSize: 45}
			],
			map: item => item.shoeSize,
			invert: false
		},
		result: [
			{name: 'Adam', shoeSize: 45},
			{name: 'Alon', shoeSize: 47.5},
			{name: 'Itay', shoeSize: 50}
		]
	}));

	// Generated by ChatGPT - 2025-05-25T23:35
	it('GPT - Sorts by numeric property descending', runTestCase({
		input: {
			array: [
				{name: 'Alon', shoeSize: 47.5},
				{name: 'Itay', shoeSize: 50},
				{name: 'Adam', shoeSize: 45}
			],
			map: item => item.shoeSize,
			invert: true
		},
		result: [
			{name: 'Itay', shoeSize: 50},
			{name: 'Alon', shoeSize: 47.5},
			{name: 'Adam', shoeSize: 45}
		]
	}));

	// Generated by ChatGPT - 2025-05-25T23:35
	it('GPT - Sorts numbers ascending by identity map', runTestCase({
		input: {
			array: [5, 1, 3, 2],
			map: n => n
		},
		result: [1, 2, 3, 5]
	}));

	// Generated by ChatGPT - 2025-05-25T23:35
	it('GPT - Sorts strings descending by identity map', runTestCase({
		input: {
			array: ['a', 'd', 'c', 'b'],
			map: s => s,
			invert: true
		},
		result: ['d', 'c', 'b', 'a']
	}));

	// Generated by ChatGPT - 2025-05-25T23:35
	it('GPT - Sorts by string length', runTestCase({
		input: {
			array: ['apple', 'a', 'banana', 'kiwi'],
			map: str => str.length
		},
		result: ['a', 'kiwi', 'apple', 'banana']
	}));

	// Generated by ChatGPT - 2025-05-25T23:35
	it('GPT - Returns empty array if input is empty', runTestCase({
		input: {
			array: [],
			map: _ => _
		},
		result: []
	}));
});
