@startuml
participant Profile_FE
participant Account_FE
participant Account_BE
participant Profile_BE

== Create Service Account ==
ServiceAccount_FE -> ServiceAccount_BE: Create new service account(email, name, claims) .
ServiceAccount_BE -> Account_BE: Create new account\n(email, _id(service account))
Account_BE --> Profile_BE: dispatch\n"On Account Created"
Profile_BE -> Profile_BE: Create Profile document\nfor new account.

== Create TOKEN for Service Account ==
ServiceAccount_FE -> ServiceAccount_BE: create token\n(TTL, _id(service account))
ServiceAccount_BE -> Account_BE: Collect Session Data

== Session Data ==
alt Create Session Data
    Account_BE -> : dispatch\n"Collect Session Data"
    Account_BE <- : SessionData[] per module
    Account_BE -> Account_BE: Aggregate SessionData\nStringify -> **Sign** ->\nZip -> Base64
end
Account_BE -> ServiceAccount_BE: session\n(signed + data)
ServiceAccount_BE -> ServiceAccount_FE: token
ServiceAccount_FE -> ServiceAccount_FE: display token in the UI
ServiceAccount_FE -> ServiceAccount_FE: Copy token and secretly give away

...
== POST Auth ==

Profile_FE -> Profile_BE: Fetch profile by sessionId
Profile_BE <-> Account_BE: validate session and\n get account _id
Profile_BE -> Profile_BE: query DB_Profile with _id
Profile_BE-> Profile_FE: DB_Profile

@enduml