import {keysToStringify, testData, TestData, TestData_Parsed} from './test-data';
import * as fs from 'fs';
import {JSONCSVModule_Class} from '../../main/modules/JSONCSVModule';
import {runSingleTestCase, TestSuite} from '../_main';

export type Input = {
	fileName: string;
	data: TestData[];
};

export type Result = undefined;
export type TestSuite_CSVWrite = TestSuite<Input, Result>;
export type TestCase_CSVWrite = TestSuite_CSVWrite['testcases'][number];

const headers: (keyof TestData)[] = ['id', 'name', 'optional', 'innerObject', 'innerArray', 'arrayOfObjects'];

const test = async (input: Input): Promise<Result> => {
	const filePath = `${__dirname}/test-files/${input.fileName}.csv`;
	const writable = fs.createWriteStream(filePath, {});
	const JSONCSV = new JSONCSVModule_Class(keysToStringify);
	await JSONCSV.writeToStream<TestData, TestData_Parsed>(writable, input.data, {headers});
	return undefined;
};

const runTestCase = (testCase: TestCase_CSVWrite) => {
	return () => runSingleTestCase(test, testCase);
};

describe('CSV - Write', () => {
	it('Writes "test.csv" from testData array', runTestCase({
		input: {
			fileName: 'test',
			data: testData
		},
		result: undefined
	}));

	// Generated by ChatGPT - 2025-05-25T23:45
	it('GPT - Writes empty file "empty.csv" with headers only', runTestCase({
		input: {
			fileName: 'empty',
			data: []
		},
		result: undefined
	}));
});
