import {TestSuite} from '../../main/testing/types';
import {keysToStringify, TestData, testData} from './test-data';
import * as fs from 'fs';
import {JSONCSVModule_Class} from '../../main/modules/JSONCSVModule';
import {runSingleTestCase} from '../_main';

export type Input = string;
export type Result = TestData[];
export type TestSuite_CSVRead = TestSuite<Input, Result>;
export type TestCase_CSVRead = TestSuite_CSVRead['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	const filePath = `${__dirname}/test-files/${input}.csv`;
	const readable = fs.createReadStream(filePath);
	const items: TestData[] = [];
	const JSONCSV = new JSONCSVModule_Class(keysToStringify);
	await JSONCSV.readFromStream(readable, (item: TestData) => {
		if (!item.optional)
			delete item.optional;
		items.push(item);
	});
	return items;
};

const runTestCase = (testCase: TestCase_CSVRead) => {
	return () => runSingleTestCase(test, testCase);
};

describe('CSV - Read', () => {
	it('Reads and parses "test.csv" into typed TestData[]', runTestCase({
		input: 'test',
		result: testData
	}));

	// Generated by ChatGPT - 2025-05-25T23:40
	it('GPT - Reads and parses "different.csv" for alternate scenario', runTestCase({
		input: 'different',
		result: [] // update once you define expected content in test-data.ts
	}));
});
