import {keysToStringify, testData, TestData, TestData_Parsed} from './test-data.js';
import * as fs from 'fs';
import {promises as fsp} from 'fs';
import path, {resolve} from 'node:path';
import assert from 'node:assert/strict';
import {JSONCSVModule_Class} from '../../main/modules/JSONCSVModule.js';
import {runSingleTestCase, TestModel} from '@nu-art/testalot';
import {___dirname} from '../../main/esm.js';
import {FileSystemUtils} from '../../main/utils/FileSystemUtils.js';

export type Input = {
	fileName: string;
	data: TestData[];
};

export type Result = (args: { input: Input }) => Promise<void>;
export type TestCase_CSVWrite = TestModel<Input, Result>;

const headers: (keyof TestData)[] = ['id', 'name', 'optional', 'innerObject', 'innerArray', 'arrayOfObjects'];
const testFilesDir = path.join(___dirname(import.meta.url), 'test-files');

const JSONCSV = new JSONCSVModule_Class(keysToStringify);

const test = async (input: Input): Promise<undefined> => {
	await fsp.mkdir(testFilesDir, {recursive: true});
	const outputPath = resolve(testFilesDir, `${input.fileName}.csv`);
	const writable = fs.createWriteStream(outputPath, {});
	await JSONCSV.writeToStream<TestData, TestData_Parsed>(writable, input.data, {headers, alwaysWriteHeaders: true});
	return undefined;
};

// Hardcoded expected CSVs (match your writer's format)
const EXPECTED_TEST_CSV =
				'id,name,optional,innerObject,innerArray,arrayOfObjects\n' +
				'0000,Adam,asd,"{""a"":10,""b"":""Po""}",[],"[{""a"":10},{""a"":20}]"\n' +
				'1111,Matan,,"{""a"":20,""b"":""Ze""}",[1],"[{""a"":20}]"\n' +
				'2222,Itay,,"{""a"":30,""b"":""Zevel""}","[1,2]",[]';

const EXPECTED_EMPTY_CSV =
				'id,name,optional,innerObject,innerArray,arrayOfObjects';


const runTestCase = (testCase: TestCase_CSVWrite) => {
	return () => runSingleTestCase(test, testCase);
};

describe('CSV - Write', () => {
	beforeEach(async () => {
		console.log(`deleting ${testFilesDir}`);
		await FileSystemUtils.folder.delete(testFilesDir);
		await FileSystemUtils.folder.create(testFilesDir);
	});

	afterEach(async () => {
		await FileSystemUtils.folder.delete(testFilesDir);
	});

	it('Writes "test.csv" from testData array', runTestCase({
		input: {
			fileName: 'test',
			data: testData
		},
		result: async () => {
			const actual = (await FileSystemUtils.file.read(resolve(testFilesDir, `test.csv`))).trim();
			assert.strictEqual(actual, EXPECTED_TEST_CSV, `CSV content mismatch`);
		},
	}));

	// Generated by ChatGPT - 2025-05-25T23:45
	it('GPT - Writes empty file "empty.csv" with headers only', runTestCase({
		input: {
			fileName: 'empty',
			data: []
		},
		result: async () => {
			const actual = (await FileSystemUtils.file.read(resolve(testFilesDir, `empty.csv`))).trim();
			assert.strictEqual(actual, EXPECTED_EMPTY_CSV, `CSV content mismatch`);
		},
	}));
});
