// version: v2;
// file: ./test/units/migration/unit-to-esm.test.ts
import {DebugFlag, LogLevel, sleep} from '@nu-art/ts-common';
import {TestModel, defaultTestProcessor, runSingleTestCase} from '@nu-art/testalot';
import {phase_Prepare, phase_ToESM} from '../../_common.js';
import {resolve} from 'path';
import {expect} from 'chai';
import {TestWorkspaceCreator} from '@nu-art/ts-common/testing/workspace-creator';
import {CommandoPool} from '@nu-art/commando';
import {BuildAndInstall} from '../../../main/build-and-install-v3.js';
import {___dirname} from '@nu-art/ts-common/esm';
import {FileSystemUtils} from '@nu-art/ts-common/utils/FileSystemUtils';

const dirname = ___dirname(import.meta.url);
DebugFlag.DefaultLogLevel = LogLevel.Verbose;

const pathToTemp = resolve(dirname, './temp');
const pathToFixtures = resolve(pathToTemp, './fixtures');
const pathToWorkspace = resolve(pathToTemp, './workspace');
const pathToPackage = resolve(pathToWorkspace, './lib-migrate');
const fixtureTemplateExtractor = new TestWorkspaceCreator(dirname, pathToFixtures);
const workspaceCreator = new TestWorkspaceCreator(pathToFixtures, pathToWorkspace);

let buildAndInstall: BuildAndInstall;

type Input = {
	fixtures: string[];          // per-test workspace overlays
	unitKey?: string;            // default: lib-migrate
	writeChanges?: boolean;      // if false, sets simulation=true and expects no file edits
};
type Output = () => Promise<void>;

// Processor
const test = async (setup: Input) => {
	// materialize test workspace for this case
	await workspaceCreator.setupWorkspace(setup.fixtures, 'lib-migrate', false);

	buildAndInstall = new BuildAndInstall({pathToProject: pathToWorkspace});
	buildAndInstall.runtimeParams.allUnits = true;
	buildAndInstall.runtimeParams.toESM = true;
	// For migration assertions we usually DO want file edits to occur
	buildAndInstall.runtimeParams.simulation = setup.writeChanges === false;

	await buildAndInstall.build();
	buildAndInstall.setPhases([[phase_Prepare], [phase_ToESM]]);
	await buildAndInstall.run();
};


type TestCase_ToESM = TestModel<Input, Output>;

const runTestCase = (testCase: TestCase_ToESM, processor = defaultTestProcessor) => () => runSingleTestCase(test, testCase, processor);

describe('Unit_NodeLib - ToESM Phase', () => {
	// @ts-ignore
	let suiteHasFailures = false;

	beforeEach(async function () {
		await FileSystemUtils.folder.delete(pathToTemp);
		// Bring in repo-wide base workspace + this suite's fixtures catalog
		await fixtureTemplateExtractor.setupWorkspace(['../../workspace-fixture.txt', 'fixtures.txt']);
		// Base workspace and base package under test
		await workspaceCreator.setupWorkspace(['workspace.txt']);
	});

	it('adds .js to relative file imports', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-rel-file.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./util.js\'');
			expect(content).to.contain('from \'../shared/helpers.js\'');
		}
	}));

	it('explicit /index.js for folder imports', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-index-resolution.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./lib/index.js\'');
		}
	}));

	it('bare package specifiers remain unchanged', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-bare-package.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'lodash\'');
		}
	}));

	// Generated by ChatGPT on 2025-11-04: cross-package relative import
	it('cross-package relative import gets remains unchanged', runTestCase({
		input: {fixtures: ['./workspace-migrate-cross-package-relative.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './packages/pkg-a/src/main/a.ts'));
			expect(content).to.contain('from \'pkg-b/file\'');
		}
	}));

	// Generated by ChatGPT on 2025-11-05 — A4
	it('explicit index (no ext) → .js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-explicit-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./lib/index.js\'');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A5
	it('trailing slash folder → /index.js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-trailing-slash.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./lib/index.js\'');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A6
	it('dot path to index (./) → /index.js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-dot-to-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./index.js\'');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A7
	it('already .js import remains unchanged', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-already-js.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./util.js\'');
			expect(content).to.not.contain('.js.js');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A8
	it('.ts and .tsx imports are rewritten to .js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-ts-tsx.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./util.js\'');
			expect(content).to.contain('from \'./Comp.js\'');
			expect(content).to.not.contain('from \'./util.ts\'');
			expect(content).to.not.contain('from \'./Comp.tsx\'');
		}
	}));

	it('relative file specifiers (no ext) are rewritten to .js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-rel-file.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./util.js\'');
			expect(content).to.contain('from \'../shared/helpers.js\'');
		}
	}));

	it('relative folder (implicit index) is rewritten to /index.js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-index-resolution.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./lib/index.js\'');
		}
	}));

	it('relative explicit index (no ext) is rewritten to .js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-explicit-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./lib/index.js\'');
		}
	}));

	it('relative folder with trailing slash resolves to /index.js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-trailing-slash.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./lib/index.js\'');
		}
	}));

	it('dot path (./) resolves to ./index.js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-dot-to-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./index.js\'');
		}
	}));

	it('already-suffixed .js imports remain unchanged (idempotent)', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-already-js.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./util.js\'');
			expect(content).to.not.contain('.js.js');
		}
	}));

	it('explicit .ts and .tsx specifiers are rewritten to .js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-ts-tsx.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./util.js\'');
			expect(content).to.contain('from \'./Comp.js\'');
			expect(content).to.not.contain('from \'./util.ts\'');
			expect(content).to.not.contain('from \'./Comp.tsx\'');
		}
	}));

	it('cross-package bare package import remains unchanged', runTestCase({
		input: {fixtures: ['./workspace-migrate-cross-package-bare.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './packages/pkg-a/src/main/a.ts'));
			expect(content).to.contain('from \'pkg-b\'');
		}
	}));

	// D1 — dynamic import with a static literal rewrites to /index.js
	it('dynamic import of folder literal rewrites to /index.js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-dyn-import-static.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('import(\'./lib/index.js\')');
		}
	}));

// D2 — dynamic import with a non-literal expression remains unchanged
	it('dynamic import with expression remains unchanged', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-dyn-import-expr.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('import(\'./lib/\' + name)');
		}
	}));

// D3 — await import("'./util'") → await import('./util.js')
	it('require() with static literal converts to await import() with .js', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-require-literal.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('await import(\'./util.js\')');
			expect(content).to.not.contain('require(\'./util\')');
		}
	}));

// D4 — await import("name") → await import(name)
	it('require() with non-literal expression converts to await import(expression)', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-require-expr.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('await import(name)');
			expect(content).to.not.contain('require(name)');
		}
	}));

// E1 — asset imports remain unchanged
	it('asset import (svg) remains unchanged', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-asset-import.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('import \'./logo.svg\'');
			expect(content).to.not.contain('.svg');
		}
	}));

// E2 — json imports remain unchanged
	it('json import remains unchanged', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-json-import.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from \'./data.json\'');
			expect(content).to.not.contain('.json.js');
		}
	}));

// F1 — type-only imports remain unchanged
	it('type-only import remains unchanged', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-type-only.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('import type { Foo } from \'./types.js\'');
		}
	}));

// G1 — idempotency: running ToESM twice is a no-op after first pass
	it('idempotency: second ToESM pass makes no further changes', runTestCase({
		input: {fixtures: ['./lib-migrate.txt', './workspace-migrate-rel-file.txt']},
		result: async () => {
			const target = resolve(pathToPackage, './src/main/a.ts');
			const once = await FileSystemUtils.file.read(target);

			const bai2 = new BuildAndInstall({pathToProject: pathToWorkspace});
			bai2.runtimeParams.allUnits = true;
			bai2.runtimeParams.simulation = false;
			await bai2.build();
			bai2.setPhases([[phase_ToESM]]);
			await bai2.run();

			const twice = await FileSystemUtils.file.read(target);
			expect(twice).to.equal(once);
		}
	}));

// P1 — __package.json gains type: module and baseline exports
	it('__package.json is enriched with type:module and baseline exports', runTestCase({
		input: {fixtures: ['./lib-migrate.txt']},
		result: async () => {
			const json = await FileSystemUtils.file.read(resolve(pathToPackage, './__package.json'));
			const pkg = JSON.parse(json);
			expect(pkg.type).to.equal('module');
			expect(pkg.exports).to.be.an('object');
			expect(pkg.exports['.']).to.deep.equal({types: './index.d.ts', import: './index.js'});
			expect(pkg.exports['./*']).to.deep.equal({types: './*.d.ts', import: './*.js'});
		}
	}));

	afterEach(function () {
		if (this.currentTest?.state === 'failed')
			suiteHasFailures = true;

		suiteHasFailures ??= false;
	});

	after(async function () {
		await sleep(1000);
		if (suiteHasFailures === false)
			await FileSystemUtils.folder.delete(pathToTemp);

		await CommandoPool.killAll();
	});
});
