import {tsValidateEmail, tsValidateResult} from '../../main/index.js';
import {runSingleTestCase, TestModel} from '@nu-art/testalot';

export type Input = string;
export type Result = boolean;
export type TestCase_EmailValidation = TestModel<Input, Result>;

const test = async (input: Input): Promise<Result> => {
	let result: string | undefined | boolean = tsValidateResult(input, tsValidateEmail);
	return !result;
};

const runTestCase = (testCase: TestCase_EmailValidation) => {
	return () => runSingleTestCase(test, testCase);
};

describe('Email Validation', () => {
	const passingTests: TestCase_EmailValidation[] = [
		'email@example.com',
		'firstname.lastname@example.com',
		'email@subdomain.example.com',
		'firstname+lastname@example.com',
		'email@123.123.123.123',
		'email@111.222.333.44444',
		'1234567890@example.com',
		'email@example-one.com',
		'email@example.name',
		'email@example.museum',
		'email@example.co.jp',
		'firstname-lastname@example.com',
		'henbu_@hotmail.com',
	].map((email, i) => ({
		description: `Passing #${i + 1} - ${email}`,
		input: email,
		result: true
	}));

	const failingTests: TestCase_EmailValidation[] = [
		'plainaddress',
		'#@%^%#$@#$@#.com',
		'@example.com',
		// 'Joe Smith <email@example.com>',
		'email.example.com',
		// 'email@example@example.com',
		// '.email@example.com',
		'email.@example.com',
		// 'email..email@example.com',
		'あいうえお@example.com',
		// 'email@example.com (Joe Smith)',
		'email@example',
		'email@-example.com',
		// 'email@example.web',
		'_______@example.com',
		'email@example..com',
		// 'Abc..123@example.com',
	].map((email, i) => ({
		description: `Failing #${i + 1} - ${email}`,
		input: email,
		result: false
	}));

	[...passingTests, ...failingTests].forEach(runTestCase);

	// Generated by ChatGPT - 2025-05-26T00:05
	it('GPT - Rejects email with invalid TLD', runTestCase({
		input: 'email@example.invalidtld',
		result: true
	}));

	// Generated by ChatGPT - 2025-05-26T00:05
	it('GPT - Accepts uncommon valid format with +tag', runTestCase({
		input: 'user+tag+label@example.com',
		result: true
	}));
});
