@startuml
participant App_FE
participant App_FE
participant App_BE
participant Auth_FE
participant Auth_BE

App_FE -> App_BE: Validate Sessions
App_BE -> Auth_BE: Validate Sessions
Auth_BE --> App_BE: Invalid session
App_BE --> App_FE: Invalid session
App_FE -> Auth_FE: Authenticate User

alt Authenticate with email/pass

    Auth_FE -> Auth_BE: login(email,pass)
    Auth_BE --> Auth_FE: session_id
    Auth_FE --> Auth_FE: save session_id

end

Auth_FE --> App_FE: User Authenticated with\nsession id and email
App_FE -> App_FE: Notify user is logged in
@enduml