import {compare, runSingleTestCase, TestSuite} from '../_main';

export type Input<T = any> = {
	one: any;
	two: any;
};

export type Result = boolean;
export type TestSuite_compare = TestSuite<Input, Result>;
export type TestCase_compare = TestSuite_compare['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return compare(input.one, input.two);
};

const runTestCase = (testCase: TestCase_compare) => {
	return () => runSingleTestCase(test, testCase);
};

describe('compare', () => {
	it('Compares identical integers', runTestCase({
		input: {one: 1, two: 1},
		result: true
	}));

	it('Compares identical numeric strings', runTestCase({
		input: {one: '1', two: '1'},
		result: true
	}));

	it('Compares different integers', runTestCase({
		input: {one: 1, two: 2},
		result: false
	}));

	it('Compares integer vs string number', runTestCase({
		input: {one: '1', two: 1},
		result: false
	}));

	it('Compares identical words', runTestCase({
		input: {one: 'test', two: 'test'},
		result: true
	}));

	it('Compares different words', runTestCase({
		input: {one: 'test1', two: 'test'},
		result: false
	}));

	it('Compares two empty arrays', runTestCase({
		input: {one: [], two: []},
		result: true
	}));

	it('Compares same one-element arrays', runTestCase({
		input: {one: ['Alon'], two: ['Alon']},
		result: true
	}));

	it('Compares different-length arrays', runTestCase({
		input: {one: ['Alon'], two: ['Alon', 'Ninio']},
		result: false
	}));

	it('Compares same objects with 1 property', runTestCase({
		input: {one: {a: 1}, two: {a: 1}},
		result: true
	}));

	it('Compares same objects with 2 properties', runTestCase({
		input: {one: {a: 1, b: '2'}, two: {a: 1, b: '2'}},
		result: true
	}));

	it('Compares nulls', runTestCase({
		input: {one: null, two: null},
		result: true
	}));

	it('Compares null and object', runTestCase({
		input: {one: null, two: {a: 1}},
		result: false
	}));

	it('Compares undefined and undefined', runTestCase({
		input: {one: undefined, two: undefined},
		result: true
	}));

	it('Compares null and undefined', runTestCase({
		input: {one: null, two: undefined},
		result: false
	}));

	// Generated by ChatGPT - 2025-05-25T23:58
	it('GPT - Compares NaN to NaN', runTestCase({
		input: {one: NaN, two: NaN},
		result: true
	}));

	// Generated by ChatGPT - 2025-05-25T23:58
	it('GPT - Compares Date objects with same time', runTestCase({
		input: {one: new Date('2022-01-01'), two: new Date('2022-01-01')},
		result: true
	}));

	// Generated by ChatGPT - 2025-05-25T23:58
	it('GPT - Compares Date objects with different times', runTestCase({
		input: {one: new Date('2022-01-01'), two: new Date('2023-01-01')},
		result: false
	}));

	// Generated by ChatGPT - 2025-05-25T23:58
	it('GPT - Compares RegExp literals with same pattern', runTestCase({
		input: {one: /abc/i, two: /abc/i},
		result: true
	}));

	// Generated by ChatGPT - 2025-05-25T23:58
	it('GPT - Compares RegExp literals with different flags', runTestCase({
		input: {one: /abc/g, two: /abc/i},
		result: false
	}));

	// Generated by ChatGPT - 2025-05-25T23:58
	it('GPT - Compares object references to same instance', runTestCase({
		input: (() => {
			const ref = {x: 1};
			return {one: ref, two: ref};
		})(),
		result: true
	}));

	// Generated by ChatGPT - 2025-05-25T23:58
	it('GPT - Compares deeply nested matching objects', runTestCase({
		input: {
			one: {a: {b: {c: [1, 2, 3]}}},
			two: {a: {b: {c: [1, 2, 3]}}}
		},
		result: true
	}));
});
