import {scrub, ScrubConfig} from '../_main.js';
import {runSingleTestCase, TestModel} from '@nu-art/testalot';

export type Input = {
	item: any;
	config?: Partial<ScrubConfig>;
};

export type Result = any;
export type TestCase_Scrub = TestModel<Input, Result>;

const test = async (input: Input): Promise<void> => {
	return scrub(input.item, input.config);
};

const runTestCase = (testCase: TestCase_Scrub) => {
	return () => runSingleTestCase(test, testCase);
};

// Shared test data
const simpleObject1 = {a: 'property A', b: true, c: 42};
const simpleObject2 = {d: 'property D', e: false, f: 360};

const compoundObject1 = {
	one: simpleObject1,
	two: simpleObject2,
	strArr: ['asd1', 'asd2'],
	objArr: [simpleObject1, simpleObject2],
};

const config_FullScrub: Partial<ScrubConfig> = {
	emptyObjects: true,
	emptyArrays: true,
	emptyStrings: true,
};

describe('scrub', () => {
	it('Simple Object - No scrub', runTestCase({
		input: {item: simpleObject1, config: config_FullScrub},
		result: simpleObject1
	}));

	it('Simple Object - Empty String', runTestCase({
		input: {item: {...simpleObject1, a: ''}, config: config_FullScrub},
		result: {b: true, c: 42}
	}));

	it('Simple Object - Undefined Property', runTestCase({
		input: {item: {...simpleObject2, d: undefined}, config: config_FullScrub},
		result: {e: false, f: 360}
	}));

	it('Simple Object - Null Property', runTestCase({
		input: {item: {...simpleObject2, d: null}, config: config_FullScrub},
		result: {e: false, f: 360}
	}));

	it('Compound Object - No Scrub', runTestCase({
		input: {item: compoundObject1, config: config_FullScrub},
		result: compoundObject1
	}));

	it('Compound Object - Undefined Property', runTestCase({
		input: {item: {...compoundObject1, three: undefined}, config: config_FullScrub},
		result: compoundObject1
	}));

	it('Compound Object - Null Property', runTestCase({
		input: {item: {...compoundObject1, three: null}, config: config_FullScrub},
		result: compoundObject1
	}));

	it('Compound Object - Inner prop with empty string', runTestCase({
		input: {item: {...compoundObject1, one: {...simpleObject1, a: ''}}, config: config_FullScrub},
		result: {
			one: {b: true, c: 42},
			two: simpleObject2,
			strArr: ['asd1', 'asd2'],
			objArr: [simpleObject1, simpleObject2],
		}
	}));

	it('Compound Object - Empty string in string array', runTestCase({
		input: {item: {...compoundObject1, strArr: [...compoundObject1.strArr, '']}, config: config_FullScrub},
		result: compoundObject1
	}));

	it('Compound Object - Undefined in obj array', runTestCase({
		input: {item: {...compoundObject1, objArr: [...compoundObject1.objArr, undefined]}, config: config_FullScrub},
		result: compoundObject1
	}));

	it('Compound Object - Empty obj in obj array', runTestCase({
		input: {item: {...compoundObject1, objArr: [...compoundObject1.objArr, {}]}, config: config_FullScrub},
		result: compoundObject1
	}));

	it('Compound Object - Empty prop in object in obj array', runTestCase({
		input: {item: {...compoundObject1, objArr: [...compoundObject1.objArr, {a: ''}]}, config: config_FullScrub},
		result: compoundObject1
	}));

	it('Compound Object - Super Complex', runTestCase({
		input: {
			item: {
				kaki: 'cf931ac531a50dfb8d18d84a9f632963',
				zevel: false,
				data: {
					'821648d51c7f1238aff85caff362f95b': {
						'0b51ea0f2bac437138757e09077f0d44': [
							{
								kishkush: '821648d51c7f1238aff85caff362f95b',
								balabush: {
									'91dd392b9f5155089d32b288be6f239f': [
										'ba40e19ea773738bae8352ee4be6e614'
									]
								}
							}
						]
					},
					'83ecf4334cdbfb320025e06a336a5461': {},
				}
			},
			config: config_FullScrub
		},
		result: {
			kaki: 'cf931ac531a50dfb8d18d84a9f632963',
			zevel: false,
			data: {
				'821648d51c7f1238aff85caff362f95b': {
					'0b51ea0f2bac437138757e09077f0d44': [
						{
							kishkush: '821648d51c7f1238aff85caff362f95b',
							balabush: {
								'91dd392b9f5155089d32b288be6f239f': [
									'ba40e19ea773738bae8352ee4be6e614'
								]
							}
						}
					]
				}
			}
		}
	}));

	// Generated by ChatGPT - 2025-05-26T00:00
	it('GPT - Removes empty string, array, and object from shallow object', runTestCase({
		input: {
			item: {
				a: '',
				b: [],
				c: {},
				d: 'valid'
			},
			config: config_FullScrub
		},
		result: {d: 'valid'}
	}));
});
