import * as fs from 'fs';
import {parse} from 'fast-csv';
import {runSingleTestCase, TestSuite} from '../_main.js';
import {StreamTest_FromTransformed, StreamTest_Items, StreamTest_Type1} from './test-helper.js';
import {expect} from 'chai';
import {___dirname} from '../../main/esm.js';
import {FileSystemUtils} from '../../main/utils/FileSystemUtils.js';
import {resolve} from 'node:path';

export type Input = string;
export type Result = StreamTest_Type1[];
export type TestSuite_Stream = TestSuite<Input, Result>;
export type TestCase_Stream = TestSuite_Stream['testcases'][number];
const dirname = ___dirname(import.meta.url);

const test = async (input: Input): Promise<Result> => {
	const inputFilePath = `${dirname}/test-files/${input}.csv`;
	const stream = fs.createReadStream(inputFilePath);
	const parser = parse({headers: true})
		.transform(StreamTest_FromTransformed);

	const items: StreamTest_Type1[] = [];

	await new Promise<void>((resolve, reject) => {
		stream
			.pipe(parser)
			.on('data', data => items.push(data))
			.on('error', reject)
			.on('finish', resolve);
	});
	return items;
};

const runTestCase = (testCase: TestCase_Stream) => {
	return () => runSingleTestCase(test, testCase);
};

const CSV_CONTENT = [
	'id,name1',
	'0000,Adam',
	'1111,Matan',
	'2222,Itay',
	'3333,Yuval',
	'4444,Harel'
].join('\n');

describe('Stream - Read CSV', () => {
	before(async () => {
		await FileSystemUtils.file.write(resolve(dirname, 'test-files/test.csv'), CSV_CONTENT);
	});

	after(async () => {
		await FileSystemUtils.folder.delete(resolve(dirname, 'test-files'));
	});


	it('Reads and transforms rows from "test.csv"', runTestCase({
		input: 'test',
		result: async (items) => expect(items).to.eql(StreamTest_Items)

	}));

	// // Generated by ChatGPT - 2025-05-26T00:10
	// it('GPT - Reads and transforms rows from "alternate.csv"', runTestCase({
	// 	input: 'alternate',
	// 	result: async (items) => expect(items).to.eql(StreamTest_Items);
	// }));
});
