import {TestSuite} from '../../main/testing/types';
import * as fs from 'fs';
import {format} from 'fast-csv';
import {runSingleTestCase} from '../../main/testing/consts';
import {StreamTest_Items, StreamTest_ToTransformed} from './test-helper';

export type Input = string;
export type Result = undefined;
export type TestSuite_StreamWrite = TestSuite<Input, Result>;
export type TestCase_StreamWrite = TestSuite_StreamWrite['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	const outputPath = `${__dirname}/test-files/${input}.csv`;
	const writeStream = fs.createWriteStream(outputPath);
	const csvStream = format({headers: true}).transform(StreamTest_ToTransformed);

	await new Promise<void>((resolve, reject) => {
		csvStream.pipe(writeStream)
			.on('error', reject)
			.on('finish', resolve);

		StreamTest_Items.forEach(item => csvStream.write(item));
		csvStream.end();
	});
};

const runTestCase = (testCase: TestCase_StreamWrite) => {
	return () => runSingleTestCase(test, testCase);
};

describe('Stream - Write CSV', () => {
	it('Writes transformed rows to "test.csv"', runTestCase({
		input: 'test',
		result: undefined
	}));

	// Generated by ChatGPT - 2025-05-26T00:13
	it('GPT - Writes transformed rows to "alternate.csv"', runTestCase({
		input: 'alternate',
		result: undefined
	}));
});
