import * as fs from 'fs';
import {parse} from 'fast-csv';
import {expect} from 'chai';
import {runSingleTestCase, TestSuite} from '../_main';
import {StreamTest_FromTransformed, StreamTest_Items, StreamTest_Type1} from './test-helper';

export type Input = string;
export type Result = undefined;
export type TestSuite_Stream = TestSuite<Input, Result>;
export type TestCase_Stream = TestSuite_Stream['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	const inputFilePath = `${__dirname}/test-files/${input}.csv`;
	const stream = fs.createReadStream(inputFilePath);
	const parser = parse({headers: true})
		.transform(StreamTest_FromTransformed);

	const items: StreamTest_Type1[] = [];

	await new Promise<void>((resolve, reject) => {
		stream
			.pipe(parser)
			.on('data', data => items.push(data))
			.on('error', reject)
			.on('finish', resolve);
	});

	expect(items).to.eql(StreamTest_Items);
	return undefined;
};

const runTestCase = (testCase: TestCase_Stream) => {
	return () => runSingleTestCase(test, testCase);
};

describe('Stream - Read CSV', () => {
	it('Reads and transforms rows from "test.csv"', runTestCase({
		input: 'test',
		result: undefined
	}));

	// Generated by ChatGPT - 2025-05-26T00:10
	it('GPT - Reads and transforms rows from "alternate.csv"', runTestCase({
		input: 'alternate',
		result: undefined // you must define `StreamTest_Items` content for alternate.csv for real assertion
	}));
});
