import {merge, runSingleTestCase, TestSuite} from '../../_main';

export type Input = {
	one: any;
	two: any;
};

export type Result = any;
export type TestSuite_merge = TestSuite<Input, Result>;
export type TestCase_merge = TestSuite_merge['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return merge(input.one, input.two);
};

const runTestCase = (testCase: TestCase_merge) => {
	return () => runSingleTestCase(test, testCase);
};

describe('merge', () => {
	it('Merges undefined with object containing undefined keys', runTestCase({
		input: {
			one: undefined,
			two: {a: undefined, b: undefined}
		},
		result: {}
	}));

	it('Merges nested object with undefined values', runTestCase({
		input: {
			one: {a: 'ok'},
			two: {b: {no: undefined, nope: undefined, nay: undefined}}
		},
		result: {a: 'ok', b: {}}
	}));

	it('Merges non-overlapping objects (a then b)', runTestCase({
		input: {one: {a: 1}, two: {b: 2}},
		result: {a: 1, b: 2}
	}));

	it('Merges non-overlapping objects (b then a)', runTestCase({
		input: {one: {b: 2}, two: {a: 1}},
		result: {a: 1, b: 2}
	}));

	it('Merges overlapping objects with override', runTestCase({
		input: {one: {a: 1, b: 1}, two: {a: 2, b: 2}},
		result: {a: 2, b: 2}
	}));

	it('Merges objects with partial undefined overrides', runTestCase({
		input: {one: {a: 2, b: undefined, c: 5}, two: {b: 1, c: 3, d: null}},
		result: {a: 2, b: 1, c: 3, d: null}
	}));

	it('Merges objects and removes undefined keys from override', runTestCase({
		input: {one: {b: 1, c: 3, d: null}, two: {a: 2, b: undefined, c: 5}},
		result: {a: 2, c: 5, d: null}
	}));

	it('Returns empty array when merging array with empty', runTestCase({
		input: {one: [1, 2, 3, 4, 5], two: []},
		result: []
	}));

	it('Returns non-empty array when base is empty', runTestCase({
		input: {one: [], two: [1, 2, 3, 4, 5]},
		result: [1, 2, 3, 4, 5]
	}));

	it('Returns override array even if base is different', runTestCase({
		input: {one: [7, 8], two: [1, 2, 3, 4, 5]},
		result: [1, 2, 3, 4, 5]
	}));

	it('Merges deeply nested object structure', runTestCase({
		input: {one: {a: {a: {}}}, two: {a: {}}},
		result: {a: {a: {}}}
	}));

	it('Merges object with number zero', runTestCase({
		input: {one: {a: 0}, two: {b: 2}},
		result: {a: 0, b: 2}
	}));

	it('Merges object with empty strings', runTestCase({
		input: {one: {a: ''}, two: {b: ''}},
		result: {a: '', b: ''}
	}));

	it('Merges primitive true values', runTestCase({
		input: {one: true, two: true},
		result: true
	}));

	it('Overrides primitive true with false', runTestCase({
		input: {one: true, two: false},
		result: false
	}));

	it('Merges nested currentPhase object', runTestCase({
		input: {
			one: {
				currentPhase: {
					name: 'Zevel',
					method: 'zevel',
					filter: {}
				}
			},
			two: {
				currentPhase: {
					name: 'Zevel2',
					method: 'zevel2',
				}
			}
		},
		result: {
			currenPhase: {
				name: 'Zevel2',
				method: 'zevel2',
				filter: {}
			}
		}
	}));

	// Generated by ChatGPT - 2025-05-25T23:50
	it('GPT - Merges nested overlapping keys recursively', runTestCase({
		input: {
			one: {a: {b: 1, c: 2}},
			two: {a: {c: 3, d: 4}}
		},
		result: {a: {b: 1, c: 3, d: 4}}
	}));

	// Generated by ChatGPT - 2025-05-25T23:50
	it('GPT - Replaces function with new value', runTestCase({
		input: {
			one: {handler: () => 'v1'},
			two: {handler: 'noop'}
		},
		result: {handler: 'noop'}
	}));
	it('Throws when merging array with object', runTestCase({
		input: {one: [7, 8], two: {}},
		result: 'Error'
	}));

	it('Throws when merging object with array', runTestCase({
		input: {one: {a: 2}, two: [7, 8]},
		result: 'Error'
	}));

	it('Throws when merging string with array', runTestCase({
		input: {one: 'a', two: [7, 8]},
		result: 'Error'
	}));

	it('Throws when merging empty string with array', runTestCase({
		input: {one: '', two: [7, 8]},
		result: 'Error'
	}));

	it('Throws when merging array with nested object array', runTestCase({
		input: {one: [7, 8], two: {a: [7, 8]}},
		result: 'Error'
	}));

	it('Throws when merging number with object', runTestCase({
		input: {one: 5, two: {a: 5}},
		result: 'Error'
	}));

	it('Throws when merging object with number', runTestCase({
		input: {one: {a: 1}, two: 1},
		result: 'Error'
	}));

	it('Throws when merging string with number', runTestCase({
		input: {one: 'one', two: 1},
		result: 'Error'
	}));

	it('Throws when merging number with string', runTestCase({
		input: {one: 1, two: 'one'},
		result: 'Error'
	}));

	it('Throws when merging 0 with string', runTestCase({
		input: {one: 0, two: 'one'},
		result: 'Error'
	}));

	it('Throws when merging boolean false with object', runTestCase({
		input: {one: false, two: {b: ''}},
		result: 'Error'
	}));

	// Generated by ChatGPT - 2025-05-25T23:55
	it('GPT - Throws when merging null with object', runTestCase({
		input: {one: null, two: {a: 1}},
		result: 'Error'
	}));

});

