packages:
  - ts-common
  - neural
  - google-services
  - firebase
  - thunderstorm
  - db-api-generator
  - storm
  - live-docs
  - user-account
  - ts-workspace
  - permissions
  - push-pub-sub
  - jira
  - bug-report
  - github
  - file-upload