// version: v2;
// file: ./test/units/migration/unit-to-esm.test.ts
import {DebugFlag, LogLevel, sleep} from '@nu-art/ts-common';
import {TestSuite} from '@nu-art/ts-common/testing/types';
import {defaultTestProcessor, runSingleTestCase} from '@nu-art/ts-common/testing/consts';
import {phase_Prepare, phase_ToESM} from '../../_common.js';
import {resolve} from 'path';
import {expect} from 'chai';
import {TestWorkspaceCreator} from '@nu-art/ts-common/testing/workspace-creator';
import {CommandoPool} from '@nu-art/commando/shell/core/CommandoPool';
import {BuildAndInstall} from '../../../main/build-and-install-v3.js';
import {___dirname} from '@nu-art/ts-common/esm';
import {FileSystemUtils} from '@nu-art/ts-common/utils/FileSystemUtils';

const dirname = ___dirname(import.meta.url);
DebugFlag.DefaultLogLevel = LogLevel.Verbose;

const pathToTemp = resolve(dirname, './temp');
const pathToFixtures = resolve(pathToTemp, './fixtures');
const pathToWorkspace = resolve(pathToTemp, './workspace');
const pathToPackage = resolve(pathToWorkspace, './lib-migrate');
const fixtureTemplateExtractor = new TestWorkspaceCreator(dirname, pathToFixtures);
const workspaceCreator = new TestWorkspaceCreator(pathToFixtures, pathToWorkspace);

let buildAndInstall: BuildAndInstall;

type Input = {
	fixtures: string[];          // per-test workspace overlays
	unitKey?: string;            // default: lib-migrate
	writeChanges?: boolean;      // if false, sets simulation=true and expects no file edits
};
type Output = () => Promise<void>;

// Processor
const test = async (setup: Input) => {
	// materialize test workspace for this case
	workspaceCreator.setupWorkspace(setup.fixtures, 'lib-migrate', false);

	buildAndInstall = new BuildAndInstall({pathToProject: pathToWorkspace});
	buildAndInstall.runtimeParams.allUnits = true;
	// For migration assertions we usually DO want file edits to occur
	buildAndInstall.runtimeParams.simulation = setup.writeChanges === false;

	await buildAndInstall.build();
	buildAndInstall.setPhases([[phase_Prepare], [phase_ToESM]]);
	await buildAndInstall.run();
};


type TestSuite_ToESM = TestSuite<Input, Output>;
type TestCase_ToESM = TestSuite_ToESM['testcases'][number];

const runTestCase = (testCase: TestCase_ToESM, processor = defaultTestProcessor) => () => runSingleTestCase(test, testCase, processor);

describe('Unit_NodeLib - ToESM Phase', () => {
	// @ts-ignore
	let suiteHasFailures = false;

	beforeEach(async function () {
		await FileSystemUtils.folder.delete(pathToTemp);
		// Bring in repo-wide base workspace + this suite's fixtures catalog
		fixtureTemplateExtractor.setupWorkspace(['../../workspace-fixture.txt', 'fixtures.txt']);
		// Base workspace and base package under test
		workspaceCreator.setupWorkspace(['workspace.txt']);
		workspaceCreator.setupWorkspace(['lib-migrate.txt'], 'lib-migrate');
	});

	it('adds .js to relative file imports', runTestCase({
		input: {fixtures: ['./workspace-migrate-rel-file.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./util.js"');
			expect(content).to.contain('from "../shared/helpers.js"');
		}
	}));

	it('explicit /index.js for folder imports', runTestCase({
		input: {fixtures: ['./workspace-migrate-index-resolution.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./lib/index.js"');
		}
	}));

	it('bare package specifiers remain unchanged', runTestCase({
		input: {fixtures: ['./workspace-migrate-bare-package.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "lodash"');
		}
	}));

	// Generated by ChatGPT on 2025-11-04: cross-package relative import
	it('cross-package relative import gets remains unchanged', runTestCase({
		input: {fixtures: ['./workspace-migrate-cross-package-relative.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './packages/pkg-a/src/main/a.ts'));
			expect(content).to.contain('from "pkg-b/file"');
		}
	}));

	// Generated by ChatGPT on 2025-11-05 — A4
	it('explicit index (no ext) → .js', runTestCase({
		input: {fixtures: ['./workspace-migrate-explicit-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./lib/index.js"');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A5
	it('trailing slash folder → /index.js', runTestCase({
		input: {fixtures: ['./workspace-migrate-trailing-slash.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./lib/index.js"');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A6
	it('dot path to index (./) → /index.js', runTestCase({
		input: {fixtures: ['./workspace-migrate-dot-to-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./index.js"');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A7
	it('already .js import remains unchanged', runTestCase({
		input: {fixtures: ['./workspace-migrate-already-js.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./util.js"');
			expect(content).to.not.contain('.js.js');
		}
	}));

// Generated by ChatGPT on 2025-11-05 — A8
	it('.ts and .tsx imports are rewritten to .js', runTestCase({
		input: {fixtures: ['./workspace-migrate-ts-tsx.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./util.js"');
			expect(content).to.contain('from "./Comp.js"');
			expect(content).to.not.contain('from "./util.ts"');
			expect(content).to.not.contain('from "./Comp.tsx"');
		}
	}));

	it('relative file specifiers (no ext) are rewritten to .js', runTestCase({
		input: {fixtures: ['./workspace-migrate-rel-file.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./util.js"');
			expect(content).to.contain('from "../shared/helpers.js"');
		}
	}));

	it('relative folder (implicit index) is rewritten to /index.js', runTestCase({
		input: {fixtures: ['./workspace-migrate-index-resolution.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./lib/index.js"');
		}
	}));

	it('relative explicit index (no ext) is rewritten to .js', runTestCase({
		input: {fixtures: ['./workspace-migrate-explicit-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./lib/index.js"');
		}
	}));

	it('relative folder with trailing slash resolves to /index.js', runTestCase({
		input: {fixtures: ['./workspace-migrate-trailing-slash.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./lib/index.js"');
		}
	}));

	it('dot path (./) resolves to ./index.js', runTestCase({
		input: {fixtures: ['./workspace-migrate-dot-to-index.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./index.js"');
		}
	}));

	it('already-suffixed .js imports remain unchanged (idempotent)', runTestCase({
		input: {fixtures: ['./workspace-migrate-already-js.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./util.js"');
			expect(content).to.not.contain('.js.js');
		}
	}));

	it('explicit .ts and .tsx specifiers are rewritten to .js', runTestCase({
		input: {fixtures: ['./workspace-migrate-ts-tsx.txt']},
		result: async () => {
			const content = await FileSystemUtils.file.read(resolve(pathToPackage, './src/main/a.ts'));
			expect(content).to.contain('from "./util.js"');
			expect(content).to.contain('from "./Comp.js"');
			expect(content).to.not.contain('from "./util.ts"');
			expect(content).to.not.contain('from "./Comp.tsx"');
		}
	}));

	afterEach(function () {
		if (this.currentTest?.state === 'failed')
			suiteHasFailures = true;

		suiteHasFailures ??= false;
	});

	after(async function () {
		await sleep(1000);
		if (suiteHasFailures === false)
			await FileSystemUtils.folder.delete(pathToTemp);

		await CommandoPool.killAll();
	});
});
