import {TestSuite} from '../../main/testing/types';
import {ReplacerV2, ReplacerV2_Input} from '../../main/replacer-v2/ReplacerV2';
import {runSingleTestCase} from '../_main';

export type Input = {
	text: string;
	input?: ReplacerV2_Input;
};

export type Result = string;
export type TestSuite_replacerV2 = TestSuite<Input, Result>;
export type TestCase_replacerV2 = TestSuite_replacerV2['testcases'][number];

const test = async (input: Input): Promise<Result> => {
	return new ReplacerV2().replace(input.text, input.input);
};

const runTestCase = (testCase: TestCase_replacerV2) => {
	return () => runSingleTestCase(test, testCase);
};

describe('replacerV2', () => {
	it('Handles string with no params', runTestCase({
		input: {
			text: 'This is a simple text',
			input: undefined
		},
		result: 'This is a simple text'
	}));

	it('Replaces a simple param', runTestCase({
		input: {
			text: 'This is a ${p} text',
			input: {p: 'PARAM'}
		},
		result: 'This is a PARAM text'
	}));

	// Generated by ChatGPT - 2025-05-26T00:18
	it('GPT - Replaces multiple parameters', runTestCase({
		input: {
			text: 'Hello ${first} ${last}!',
			input: {first: 'Jane', last: 'Doe'}
		},
		result: 'Hello Jane Doe!'
	}));

	// Generated by ChatGPT - 2025-05-26T00:18
	it('GPT - Leaves missing param untouched', runTestCase({
		input: {
			text: 'Hello ${missing}!',
			input: {}
		},
		result: 'Hello ${missing}!'
	}));

	// Generated by ChatGPT - 2025-05-26T00:18
	it('GPT - Escapes single dollar signs', runTestCase({
		input: {
			text: 'Cost is \\$100 and param is ${x}',
			input: {x: 'YES'}
		},
		result: 'Cost is \\$100 and param is YES'
	}));

	// Generated by ChatGPT - 2025-05-26T00:18
	it('GPT - Handles numeric replacements', runTestCase({
		input: {
			text: 'Pi is approximately ${pi}',
			input: {pi: 3.14}
		},
		result: 'Pi is approximately 3.14'
	}));
});
